site_name: City Building Energy Model (CityBEM) V2
site_url: https://saeed-rayegan.github.io/CityBEM-Docs/ # Added site URL for GitHub Pages
theme:
  name: material
  title: CityBEM
  logo: assets/citybem_logo.png
  favicon: assets/citybem_logo.png
  features:
    - content.code.annotate
    - content.tabs
    - content.cards
    - content.grid
    - navigation.instant
    - navigation.title
  hide:
    - header
    - footer

extra:
  alternate_site_name: CityBEM

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Run CityBEM: run_citybem.md
  - Input Data: data_inputs.md
  - Outputs: outputs.md
  - City Solar Radiation Modeling: solar_radiation.md
  - Building Energy Modeling: building_energy_modeling.md
  - Rooftop PV Model: pv_model.md
  - Microclimate Co-Simulation: microclimate.md
  - Test Cases:
      - Rooftop PV Montreal Case: examples/rooftoppv_montreal.md
  - Publications: publications.md
  - About Us: about.md
  - Contact: contact.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js